# Generated by Django 5.0.6 on 2024-09-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='kategori_dituju',
            field=models.CharField(choices=[('Kepala Sekolah', 'Kepala Sekolah'), ('Guru', 'Guru'), ('TU', 'TU'), ('Siswa', 'Siswa')], default='Siswa', max_length=20),
        ),
    ]
